version: '3.8'

volumes:
  mysql:
    driver: local

services:
  database:
    image: mysql:latest
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ecommerce
    volumes:
      - mysql:/var/lib/mysql